### ISSUE TITLE
Fatal IO Safety Violation in Rust 1.81.0

### ISSUE THREAD

**Issue by jasondeewright** [azriel91/ssh_jumper#5]
This package seems to have started panicking with an IO Safety error with a recent version. I have a simple test written that should be passing. It's based largely on the example in the readme.

> fatal runtime error: IO Safety violation: owned file descriptor already closed

The crate was working for me a few months ago. I suspect a recent version of Rust has triggered the issue. I'm very new to Rust, and haven't been able to glean much more. Using the debugger in RustRover I was able to isolate it to the `channel_direct_tcpip` method. Hope this helps.

```
    macro_rules! tokio_await {
        ($x:expr) => {
            tokio::runtime::Builder::new_current_thread().enable_all().build().unwrap().block_on($x)
        };
    }

    #[test]
    fn test_ssh_jumper() {
        use std::borrow::Cow;
        use ssh_jumper::{
            model::{HostAddress, HostSocketParams, JumpHostAuthParams, SshTunnelParams},
            SshJumper
        };

        let (local_socket_addr, _ssh_forwarder_end_rx) = {
            let jump_host = HostAddress::HostName(Cow::Borrowed("localhost"));
            let jump_host_auth_params = JumpHostAuthParams::password(
                Cow::Borrowed("jumpuser"),
                Cow::Borrowed("jumppassword"),
            );
            let target_socket = HostSocketParams {
                address: HostAddress::HostName(Cow::Borrowed("mysql")),
                port: 3306,
            };
            let ssh_params =
                SshTunnelParams::new(jump_host, jump_host_auth_params, target_socket)
                    .with_jump_host_port(10022);

            tokio_await!(SshJumper::open_tunnel(&ssh_params)).unwrap()
        };

        assert!(local_socket_addr.port() > 0);
    }
```

Here's the docker-compose file
```
services:
  ssh_tunnel:
    image: lscr.io/linuxserver/openssh-server:latest
    links:
      - mysql
    ports:
      - 10022:2222
    environment:
      PASSWORD_ACCESS: true
      USER_NAME: jumpuser
      USER_PASSWORD: jumppassword

  mysql:
    image: bitnami/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      SQL_MODE: ""
      MYSQL_DATABASE: testdb
```

Let me know if I can provide any more information
